export const acceptedPlugins = {
  linux: [
    { name: "Bash", flags: ["PID"] },
    { name: "Capabilities", flags: ["PID"] },
    { name: "Capabilities Data", flags: ["PID"] },
    { name: "Taskdata", flags: ["PID"] },
    { name: "Check Afinfo", flags: ["PID"] },
    { name: "Check Creds", flags: ["PID"] },
    { name: "Check Idt", flags: ["PID"] },
    { name: "Check Modules", flags: ["PID"] },
    { name: "Check Syscall", flags: ["PID"] },
    { name: "Elfs", flags: ["PID"] },
    { name: "Envars", flags: ["PID"] },
    { name: "Iomem", flags: ["PID"] },
    { name: "Keyboard Notifiers", flags: ["PID"] },
    { name: "Kmsg", flags: ["PID"] },
    { name: "ABCKmsg", flags: ["PID"] },
    { name: "Desc State Enum", flags: ["PID"] },
    { name: "Kmsg Five Ten", flags: ["PID"] },
    { name: "Kmsg Legacy", flags: ["PID"] },
    { name: "Lsmod", flags: ["PID"] },
    { name: "Malfind", flags: ["PID", "dump"] },
    { name: "Mount Info", flags: ["PID"] },
    { name: "Mount Info Data", flags: ["PID"] },
    { name: "Proc", flags: ["PID"] },
    { name: "Psaux", flags: ["PID"] },
    { name: "Pslists", flags: ["PID"] },
    { name: "Psscan", flags: ["PID", "dump"] },
    { name: "Desc Exit State Enum", flags: ["PID"] },
    { name: "Pstree", flags: ["PID"] },
    { name: "Sockstat", flags: ["PID"] },
    { name: "Sock Handlers", flags: ["PID"] },
    { name: "Tty Check", flags: ["PID"] },
    { name: "Vmayarascan", flags: ["PID"] }
  ],
  mac: [
    { name: "Bash", flags: ["PID"] },
    { name: "Check Syscall", flags: ["PID"] },
    { name: "Check Trap Table", flags: ["PID"] },
    { name: "Ifconfig", flags: ["PID"] },
    { name: "Kauth Listeners", flags: ["PID"] },
    { name: "Kauth Scopes", flags: ["PID"] },
    { name: "Kevents", flags: ["PID"] },
    { name: "List Files", flags: ["PID"] },
    { name: "Lsmod", flags: ["PID"] },
    { name: "Lsof", flags: ["PID"] },
    { name: "Malfind", flags: ["PID", "dump"] },
    { name: "Mount", flags: ["PID"] },
    { name: "Netstat", flags: ["PID"] },
    { name: "Proc Maps", flags: ["PID"] },
    { name: "Psaux", flags: ["PID"] },
    { name: "Pslist", flags: ["PID"] },
    { name: "Pstree", flags: ["PID"] },
    { name: "Socket Filters", flags: ["PID"] },
    { name: "Timers", flags: ["PID"] },
    { name: "Trustedbsd", flags: ["PID"] },
    { name: "VFSevents", flags: ["PID"] }
  ],
  windows: [
    { name: "cmdline", flags: ["PID", "dump"] },
    { name: "dlllist", flags: ["PID", "dump"] },
    { name: "dumpfiles", flags: ["PID", "dump"] },
    { name: "envars", flags: ["PID"] },
    { name: "getsids", flags: ["PID"] },
    { name: "handles", flags: ["PID"] },
    { name: "ldrmodules", flags: ["PID"] },
    { name: "malfind", flags: ["PID", "dump"] },
    { name: "memmap", flags: ["PID", "dump"] },
    { name: "privileges", flags: ["PID"] },
    { name: "psList", flags: ["PID", "dump"] },
    { name: "psscan", flags: ["PID", "dump"] },
    { name: "pstree", flags: ["PID"] },
    { name: "sessions", flags: ["PID"] }
  ]
};
